/** Writes solana/programs/roulette/src/spots.rs from the engine's bet-spot catalogue, so the program and the game agree. */
import { BET_SPOTS, maxForSpot } from '../src/engine';

export function spotsRust(): string {
  const rows = BET_SPOTS.map((s) => {
    const mask = s.numbers.reduce((m, n) => m | (1n << BigInt(n)), 0n);
    return `    Spot { mask: 0x${mask.toString(16)}, payout: ${s.payout}, max_dollars: ${maxForSpot(s) / 100} }, // ${s.id}`;
  });
  return `//! GENERATED by packages/chain/scripts/gen-spots.ts from @roulette/engine BET_SPOTS — do not edit.

/// One bet spot: the numbers it covers (bit n = number n), winnings per unit staked, and the table limit in dollars.
pub struct Spot { pub mask: u64, pub payout: u64, pub max_dollars: u32 }

pub const SPOT_COUNT: usize = ${BET_SPOTS.length};

pub const SPOTS: [Spot; SPOT_COUNT] = [
${rows.join('\n')}
];
`;
}

if (import.meta.main) {
  await Bun.write(new URL('../../program/programs/roulette/src/spots.rs', import.meta.url), spotsRust());
  console.log(`spots.rs written (${BET_SPOTS.length} spots)`);
}
